In [2]:
import numpy as np

class DataAnalytics:
    def __init__(self):
        self.array = None


    def create(self):
        print("\nSelect the type of array to create : ")
        print("1. 1D Array")
        print("2. 2D Array")
        print("3. 3D Array")

        ch = int(input("\nEnter your choice : "))

        if ch == 1:
            self.array = np.array(list(map(int, input("\nEnter number : ").split())))
            print("Array created successfully ",self.array)

        elif ch == 2:
            row = int(input("\nEnter number of rows : "))
            col = int(input("Enter number of columns : "))

            ele = np.array(list(map(int, input(f"\nEnter {row*col} elements : ").split())))
            self.array = ele.reshape(row,col)

            print("Array created successfully ",self.array)

        elif ch == 3:
            depth = int(input("\nEnter Depth : "))
            row = int(input("Enter number of rows : "))
            column = int(input("Enter number of columns : "))

            data = np.array(list(map(int,input(f"\nEnter {depth*row*column} elements: ").split())))
            self.array = data.reshape(depth,row,column)

            print("Array created successfully ",self.array)

        else:
            print("\nInvalid Choice..........")
            return

        self.operations()



    def operations(self):
        while True:
            print("\nSelect operation to perform : ")
            print("1. Indexing")
            print("2. Slicing")
            print("3. Go Back")
    
            ch = int(input("Enter your choice : "))

            if ch == 1:
                if self.array.ndim == 1:
                    i = int(input("Enter index : "))
                    print("\nElement = ", self.array[i])

                elif self.array.ndim == 2:
                    r = int(input("Enter row index : "))
                    c = int(input("Enter column index : "))
                    print("\nElement = ", self.array[r, c])

                elif self.array.ndim == 3:
                    d = int(input("Enter depth index : "))
                    r = int(input("Enter row index : "))
                    c = int(input("Enter column index : "))
                    print("\nElement = ", self.array[d, r, c])

            elif ch == 2:
                if self.array.ndim == 1:
                    s, e = map(int, input("\nEnter the range (Start : End) : ").split(":"))
                    print("\nSliced Array : ")
                    print(self.array[s:e])

                elif self.array.ndim == 2:
                    rs, re = map(int, input("\nEnter the row range (Start : End) : ").split(":"))
                    cs, ce = map(int, input("Enter the column range (Start : End) : ").split(":"))
    
                    print("\nSliced Array : ")
                    print(self.array[rs:re, cs:ce])

                elif self.array.ndim == 3:
                    ds, de = map(int, input("\nEnter the depth range (Start : End) : ").split(":"))
                    rs, re = map(int, input("Enter the row range (Start : End) : ").split(":"))
                    cs, ce = map(int, input("Enter the column range (Start : End) : ").split(":"))
    
                    print("\nSliced Array : ")
                    print(self.array[ds:de, rs:re, cs:ce])

    
            elif ch == 3:
                break



    def math_operation(self):
        print("\nChoose operation : ")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")

        ch = int(input("\nEnter your choice : "))

        other_arr = np.array(list(map(int, input(f"\nEnter the same-size array elements ({self.array.size}) : ").split()))).reshape(self.array.shape)

        print("\nOriginal array : ", self.array)
        print("\nSecond array : ", other_arr)

        if ch == 1:
            print("\nAddition : ", self.array + other_arr)

        elif ch == 2:
            print("\nSubtraction : ", self.array - other_arr)

        elif ch == 3:
            print("\nMultiplication : ", self.array * other_arr)

        elif ch == 4:
            print("\nDivision : ", self.array / other_arr)

        else:
            print("\nInvalid Choice.........")



    def combine_split_array(self):
        print("\nChoose an operation :")
        print("1. Combine Arrays")
        print("2. Split Array")

        ch = int(input("\nEnter your choice : "))

        if ch == 1:
            other_arr = np.array(list(map(int, input(f"\nEnter the same-size array elements ({self.array.size}) : ").split()))).reshape(self.array.shape)

            print("\nOriginal array : \n", self.array)
            print("\nSecond array : \n", other_arr)

            print("\nCombine array : \n",np.concatenate((self.array, other_arr)))

        elif ch == 2:
            print("\nOriginal array : ", self.array)

            if self.array.ndim == 1:
                n = int(input("\nEnter the number of splits : "))
                print("\nSplit Array : ", np.array_split(self.array, n))

            elif self.array.ndim == 2:
                v = int(input("\nEnter the number of splits : "))
                print("\nSplit Array (vertical) : ", np.split(self.array, v))

            elif self.array.ndim == 3:
                d = int(input("\nEnter the number of splits : "))
                print("\nSplit Array (depth) : ", np.array_split(self.array, d))


        else:
            print("\nInvalid choice..........")



    def search_sort_filter(self):
        print("\nChoose an operation :")
        print("1. Search a Value")
        print("2. Sort the Array")
        print("3. Filter Values")

        ch = int(input("\nEnter your choice : "))

        if ch == 1:
            print("\nOriginal array : \n", self.array)
            
            value = int(input("\nEnter the value to search : "))
            if np.any(self.array == value):
                print(f"\nValue {value} at index : ", np.where(self.array == value))
            else:
                print(f"\nValue {value} not found....")

        elif ch == 2:
            print("\nOriginal array : \n", self.array)
            print("\nsorted array (row-wise) : \n", np.sort(self.array))

        elif ch == 3:
            print("\nOriginal array : \n", self.array)

            value = int(input("\nEnter the value to filter : "))
            print(f"\nFiltered values greater than {value} : ", self.array[self.array > value])


        else:
            print("\nInvalid choice..........")



    def aggregates(self):
        print("\nChoose an operation :")
        print("1. Sum")
        print("2. Mean")
        print("3. Median")
        print("4. Standard Deviation")
        print("5. Variance")
        print("6. Correlation coefficient")
        print("7. Minimum and Maximum Values")
        
        ch = int(input("\nEnter your choice : "))

        if ch == 1:
            print("\nSum of array elements : ", np.sum(self.array))

        elif ch == 2:
            print("\nMean of array elements : ", np.mean(self.array))

        elif ch == 3:
            print("\nMedian of array elements : ", np.median(self.array))

        elif ch == 4:
            print("\nStandard Deviation of array elements : ", np.std(self.array))

        elif ch == 5:
            print("\nVariance of array elements : ", np.var(self.array))

        elif ch == 6:
            if self.array.ndim != 2:
                print("\nCorrelation works only for 2D arrays......")
                return

            print("\nCorrelation Coefficient : ", np.corrcoef(self.array))

        elif ch == 7:
            print("\nMinimum value in array : ", np.min(self.array))
            print("\nMaximum value in array : ", np.max(self.array))

        

        else:
            print("\nInvalid choice...........")



In [3]:
obj = DataAnalytics()

print("*" * 50)
print("    WELCOME TO NUMPY DATA ANALYZER")
print("*" * 50)
while True:
    print("MAIN MENU")
    print("1. Create a Numpy Array")
    print("2. Perform Mathematical Operations")
    print("3. Combine or Split Arrays")
    print("4. Search, Sort, or Filter Arrays")
    print("5. Compute Aggregates and Statistics")
    print("6. Exit")

    choice = int(input("Enter your choice : "))

    if choice == 1:
        obj.create()

    elif choice == 2:
        obj.math_operation()

    elif choice == 3:
        obj.combine_split_array()

    elif choice == 4:
        obj.search_sort_filter()

    elif choice == 5:
        obj.aggregates()
        
    elif choice == 6:
        print("\nThank you........")
        break
    
    else:
        print("\nInvalid Choice........") 

**************************************************
    WELCOME TO NUMPY DATA ANALYZER
**************************************************
MAIN MENU
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit

Select the type of array to create : 
1. 1D Array
2. 2D Array
3. 3D Array
Array created successfully  [[1 3 5]
 [6 8 2]
 [4 8 9]]

Select operation to perform : 
1. Indexing
2. Slicing
3. Go Back

Element =  2

Select operation to perform : 
1. Indexing
2. Slicing
3. Go Back
MAIN MENU
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit

Choose operation : 
1. Addition
2. Subtraction
3. Multiplication
4. Division

Original array :  [[1 3 5]
 [6 8 2]
 [4 8 9]]

Second array :  [[1 3 4]
 [2 5 6]
 [4 2 7]]

Addition :  [[ 2  6  9]
 [ 8 13  8]
 [ 8 10 16]]
MAIN MENU
1. Cre